# Generated by Django 4.2.20 on 2025-05-28 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0003_event_enseignant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='event',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
