# Generated by Django 4.2.20 on 2025-05-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='order_position',
        ),
    ]
