# Generated by Django 4.2.20 on 2025-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
