# Generated by Django 4.2 on 2025-05-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_alter_contenu_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenus', to='cours.module'),
        ),
    ]
