# Generated by Django 4.2.21 on 2025-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_quizresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenu',
            name='pdf',
        ),
        migrations.AddField(
            model_name='cours',
            name='category',
            field=models.CharField(choices=[('sciences', 'Sciences'), ('languages', 'Languages'), ('devweb', 'Web Development'), ('cybersecurity', 'Cybersecurity'), ('machine_learning', 'Machine Learning')], default='sciences', max_length=50),
        ),
        migrations.AddField(
            model_name='cours',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='cours',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
