# Generated by Django 4.2.21 on 2025-05-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0008_remove_contenu_pdf_cours_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='imageUrl',
            new_name='image',
        ),
    ]
