# Generated by Django 4.2.20 on 2025-05-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_rename_imageurl_cours_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='category',
            field=models.CharField(choices=[('sciences', 'Sciences'), ('languages', 'Languages'), ('devweb', 'Web Development'), ('cybersecurity', 'Cybersecurity'), ('machine_learning', 'Machine Learning')], max_length=50),
        ),
    ]
