# Generated by Django 4.2.20 on 2025-05-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('APPRENANT', 'Apprenant')], default='APPRENANT', max_length=20),
        ),
    ]
